version: '3.9'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    container_name: django_app_prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ../.env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - mysql
      - redis

  celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    container_name: celery_beat_prod
    command: celery -A config beat --loglevel=info
    env_file:
      - ../.env
    depends_on:
      - web
      - mysql
      - redis

  redis:
    image: redis:7
    container_name: redis_prod

  mysql:
    image: mysql:8
    container_name: mysql_prod
    restart: always
    env_file:
      - ../.env
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web


volumes:
  static_volume:
  media_volume:
  mysql_data:
